# Generated by Django 4.0.1 on 2022-02-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profie_pic',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
