# Generated by Django 4.0.1 on 2022-02-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customer_age_customer_profie_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
