# Generated by Django 4.0.1 on 2022-02-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
